config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    get "login", to: "users/sessions#new"
    post "login", to: "users/sessions#create"
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
    delete "signout", to: "users/sessions#destroy"
  end
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
end

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, theme: "twitter-bootstrap-3" %>
<% end %>

app/views/shared/_post_form.html.erb
<%= tinymce %>
<%= form_for post do |f| %>
  <div class="field">
    <%= f.label :title, t(".title") %>
    <%= f.text_field :title, placeholder: t(".add_title") %>
    <%= f.label :content, t(".content") %>
    <%= f.text_area :content, placeholder: t(".compose"), class: "tinymce" %>
    <%= f.label :all_tags, t(".tag") %>
    <%= f.text_field :all_tags, placeholder: t(".add_tag") %>
  </div>
  <%= f.submit t(".post"), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path @user %>">
    <strong id="following" class="stat">
      <%= @user.following.size %>
    </strong>
    <%= t ".following" %>
  </a>
  <a href="<%= followers_user_path @user %>">
    <strong id="followers" class="stat">
      <%= @user.followers.size %>
    </strong>
    <%= t ".followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info col-md-12">
  <div class="col-md-6">
    <%= link_to image_tag(@user.avatar, size: Settings.user.avt_size_150), @user %>
  </div>
  <div class="col-md-6">
    <div class="username-profile">
      <%= @user.name %>
    </div>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
    <%= render "users/follow_form" if user_signed_in? %>
  </div>

</div>