config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    get "login", to: "users/sessions#new"
    post "login", to: "users/sessions#create"
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
    delete "signout", to: "users/sessions#destroy"
  end
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  scope :order_by_desc, ->{order created_at: :desc}
  scope :search, ->(search){where "title LIKE ? OR content LIKE ?",
    "%#{search}%", "%#{search}%"}
  mount_uploader :picture, PictureUploader

  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true

  def all_tags
    tags.map(&:name).join(", ")
  end

  def all_tags=names
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def count_post
    Post.count
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: :destroy
  before_action :find_post, only: [:show, :edit, :update]
  # before_action :authenticate_user!

  def index
    @posts = Post.search(params[:q]).order(:title).page(params[:page])
      .per Settings.user.per_page
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = t ".created"
      redirect_to root_url
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def show
  end

  def destroy
    @post.destroy
    flash[:success] = t ".delete"
    redirect_to request.referrer || root_url
  end

  def edit
  end

  def update
    if @post.update_attributes post_params
      flash[:success] = t ".update_post"
      redirect_to @post
    else
      flash.now[:danger] = t ".update_fail"
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit :title, :content, :picture, :all_tags
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end

  def find_post
    @post = Post.find_by id: params[:id]
  end
end

app/views/posts/_post.html.erb
<div class="well">
  <div class="media-body">
    <div id="post-<%= post.id %>" class="lay_id">
      <div class="col-md-12">
        <div class="col-md-1">
          <%= link_to image_tag(post.user.avatar, size: Settings.user.avt_size_50),
            post.user %>
        </div>
        <div class="col-md-11">
          <span class="user-name">
            <%= link_to post.user.name, post.user %>
          </span>
          <span class="timestamp">
            <%= link_to post_path(post), class: "timestamp" do %>
              <%= t ".posted" %> <%= time_ago_in_words post.created_at %>
                <%= t ".ago" %>
              <% if user_signed_in? %>
                <% if current_user == post.user || current_user.is_admin? %>
                <div class="text-right">
                    <%= link_to t(".edit"), edit_post_path(post) %>
                    <%= link_to t(".delete"), post, method: :delete,
                      data: {confirm: t(".sure")} %>
                </div>
                <% end %>
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
      <span class="content">
        <div class="post-title">
          <%= post.title %>
        </div>
        <%= post.content.html_safe %>
        <div class="tagged-post">
          <% post.tags.each do |tag| %>
            <%= link_to "#"+tag.name, tag %>
          <% end %>
        </div>
        <div class="image-post">
          <%= image_tag post.picture.url if post.picture? %>
        </div>
      </span>
      <% if user_signed_in? %>
        <% if (user_signed_in? && (current_user.following?(post.user) ||
          current_user == post.user)) || current_user.is_admin? %>
          <button class="toggle-comment btn btn-outline-primary">
            <span class="glyphicon glyphicon-comment"></span>
            <%= t(".comment") %>
          </button>
          <div class="comment-post">
            <div class="ds">
              <%= render partial: "comments/comment", collection: post.comments,
                as: "comment" %>
            </div>
              <%= form_for [post, post.comments.build], remote: true do |f| %>
                <div class="col-md-12">
                  <div class="avatar-user">
                    <%= image_tag current_user.avatar, size: Settings.user.avt_size_40 %>
                  </div>
                  <div class="input-group">
                    <%= f.text_field :content, placeholder: t(".add_comment"),
                      class: "form-control comment-field" %>
                    <div class="input-group-btn">
                      <%= f.submit t(".add"), class: "btn btn-default" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= tinymce %>
    <%= form_for @post do |f| %>
      <div class="field">
        <%= f.label :title, t(".title") %>
        <%= f.text_field :title %>
        <%= f.label :content, t(".content") %>
        <%= f.text_area :content, class: "tinymce" %>
        <%= f.label :all_tags, t(".tag") %>
        <%= f.text_field :all_tags %>
      </div>
      <%= f.submit t(".update"), class: "btn btn-primary" %>
      <span class="picture">
        <%= f.file_field :picture %>
      </span>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="well">
  <div class="media-body">
    <div id="post-<%= post.id %>">
      <div class="col-md-12">
        <div class="col-md-1">
          <%= link_to image_tag(post.user.avatar, size: Settings.user.avt_size_50),
            post.user %>
        </div>
        <div class="col-md-11">
          <span class="user-name">
            <%= link_to post.user.name, post.user %>
          </span>
          <span class="timestamp">
            <%= link_to post_path(post), class: "timestamp" do %>
              <%= t ".posted" %> <%= time_ago_in_words post.created_at %>
                <%= t ".ago" %>
              <% if user_signed_in?  %>
                <% if current_user == post.user || current_user.is_admin? %>
                <div class="text-right">
                    <%= link_to t(".edit"), edit_post_path(post) %>
                    <%= link_to t(".delete"), post, method: :delete,
                      data: {confirm: t(".sure")} %>
                </div>
                <% end %>
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
      <span class="content">
        <div class="post-title">
          <%= post.title %>
        </div>
        <%= post.content %>
        <div class="tagged-post">
          <% post.tags.each do |tag| %>
            <%= link_to "#"+tag.name, tag %>
          <% end %>
        </div>
        <div class="image-post">
          <%= image_tag post.picture.url if post.picture? %>
        </div>
      </span>
    </div>
  </div>
</div>
<% end %>
<%= paginate @posts, theme: "twitter-bootstrap-3" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render "post", post: @post %>
  </div>
</div>