config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    get "login", to: "users/sessions#new"
    post "login", to: "users/sessions#create"
    get "signup", to: "users/registrations#new"
    post "signup", to: "users/registrations#create"
    delete "signout", to: "users/sessions#destroy"
  end
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  <p><%= t ".author" %><%= link_to t(".name"), "http://fb.com/storm291" %></p>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t(".mlog"), root_path, class: "logo" %>
      <div class="input-group stylish-input-group">
        <%= form_tag posts_path, method: :get do %>
          <%= text_field_tag :q, params[:q], placeholder: "Search",
            class: "form-control" %>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home"></span>
              <%= t ".home" %>
            <% end %>
          </li>
          <li>
            <%= link_to help_path do %>
              <span class="glyphicon glyphicon-question-sign"></span>
              <%= t ".help" %>
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
              <span class="glyphicon glyphicon-briefcase"></span>
              <%= t ".user" %>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to user_path(current_user) do %>
                  <span class="glyphicon glyphicon-user"></span>
                  <%= t ".profile" %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path do %>
                  <span class="glyphicon glyphicon-cog"></span>
                  <%= t ".setting" %>
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to signout_path, method: :delete do %>
                  <span class="glyphicon glyphicon-off"></span>
                  <%= t ".logout" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to t(".signup"), signup_path,
                class: "btn btn-default btn-outline btn-circle collapsed" %>
            </li>
            <li>
              <%= link_to t(".signin"), login_path,
                class: "btn btn-default btn-outline btn-circle collapsed" %>
            </li>
          </ul>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div id="message-appli" class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>